name: fpaint
description: "A feature-rich drawing and painting application built with Flutter that allows users to create digital artwork on any platform - iOS, Android, macOS, Windows, Linux, and Web - from a single code base."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# Repository information
repository: https://github.com/vteam-com/fPaint
homepage: https://github.com/vteam-com/fPaint
issue_tracker: https://github.com/vteam-com/fPaint/issues

version: 1.2.1+1

environment:
  sdk: ">=3.11.4"
  flutter: ">=3.41.6"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  archive: ^4.0.9
  file_picker: ^11.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.4
  image: ^4.8.0
  intl: any
  logging: any
  material_symbols_icons: ^4.2928.1
  multi_split_view: any
  package_info_plus: ^9.0.1
  pasteboard: ^0.5.0
  path_provider: any
  provider: any
  shared_preferences: ^2.5.5
  super_clipboard: any
  url_launcher: any
  vector_math: ^2.2.0
  web: any
  window_manager: ^0.5.1
  xml: any

dev_dependencies:
  analyzer: any
  build_runner: any
  coverage: any
  flutter_launcher_icons: any
  flutter_lints: any
  flutter_test:
    sdk: flutter
  mockito: any
  nested: any

# The following section is specific to Flutter packages.
flutter:
  config:
    enable-swift-package-manager: false

  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/icons/
    - assets/images/platforms/
    - assets/test/

# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios:
    remove_alpha_ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/app_icon.png"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
  macos:
    generate: true
    image_path: "assets/app_icon.png"
