// Mocks generated by Mockito 5.4.6 from annotations
// in fpaint/test/widgets/color_selector_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:typed_data' as _i16;
import 'dart:ui' as _i3;

import 'package:fpaint/helpers/color_helper.dart' as _i15;
import 'package:fpaint/models/canvas_resize.dart' as _i14;
import 'package:fpaint/models/fill_model.dart' as _i5;
import 'package:fpaint/models/selector_model.dart' as _i6;
import 'package:fpaint/panels/tools/flood_fill.dart' as _i8;
import 'package:fpaint/providers/app_preferences.dart' as _i2;
import 'package:fpaint/providers/app_provider.dart' as _i10;
import 'package:fpaint/providers/layers_provider.dart' as _i4;
import 'package:fpaint/providers/shell_provider.dart' as _i12;
import 'package:fpaint/providers/undo_provider.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;
import 'package:shared_preferences/shared_preferences.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppPreferences_0 extends _i1.SmartFake implements _i2.AppPreferences {
  _FakeAppPreferences_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeOffset_1 extends _i1.SmartFake implements _i3.Offset {
  _FakeOffset_1(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeLayersProvider_2 extends _i1.SmartFake implements _i4.LayersProvider {
  _FakeLayersProvider_2(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeFillModel_3 extends _i1.SmartFake implements _i5.FillModel {
  _FakeFillModel_3(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeSelectorModel_4 extends _i1.SmartFake implements _i6.SelectorModel {
  _FakeSelectorModel_4(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeUndoProvider_5 extends _i1.SmartFake implements _i7.UndoProvider {
  _FakeUndoProvider_5(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeColor_6 extends _i1.SmartFake implements _i3.Color {
  _FakeColor_6(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeRegion_7 extends _i1.SmartFake implements _i8.Region {
  _FakeRegion_7(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeSharedPreferences_8 extends _i1.SmartFake implements _i9.SharedPreferences {
  _FakeSharedPreferences_8(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeSize_9 extends _i1.SmartFake implements _i3.Size {
  _FakeSize_9(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeLayerProvider_10 extends _i1.SmartFake implements _i4.LayerProvider {
  _FakeLayerProvider_10(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeImage_11 extends _i1.SmartFake implements _i3.Image {
  _FakeImage_11(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [AppProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppProvider extends _i1.Mock implements _i10.AppProvider {
  MockAppProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppPreferences get preferences =>
      (super.noSuchMethod(
            Invocation.getter(#preferences),
            returnValue: _FakeAppPreferences_0(
              this,
              Invocation.getter(#preferences),
            ),
          )
          as _i2.AppPreferences);

  @override
  _i3.Offset get canvasOffset =>
      (super.noSuchMethod(
            Invocation.getter(#canvasOffset),
            returnValue: _FakeOffset_1(this, Invocation.getter(#canvasOffset)),
          )
          as _i3.Offset);

  @override
  _i4.LayersProvider get layers =>
      (super.noSuchMethod(
            Invocation.getter(#layers),
            returnValue: _FakeLayersProvider_2(
              this,
              Invocation.getter(#layers),
            ),
          )
          as _i4.LayersProvider);

  @override
  _i5.FillModel get fillModel =>
      (super.noSuchMethod(
            Invocation.getter(#fillModel),
            returnValue: _FakeFillModel_3(this, Invocation.getter(#fillModel)),
          )
          as _i5.FillModel);

  @override
  _i6.SelectorModel get selectorModel =>
      (super.noSuchMethod(
            Invocation.getter(#selectorModel),
            returnValue: _FakeSelectorModel_4(
              this,
              Invocation.getter(#selectorModel),
            ),
          )
          as _i6.SelectorModel);

  @override
  bool get isPreferencesLoaded =>
      (super.noSuchMethod(
            Invocation.getter(#isPreferencesLoaded),
            returnValue: false,
          )
          as bool);

  @override
  _i7.UndoProvider get undoProvider =>
      (super.noSuchMethod(
            Invocation.getter(#undoProvider),
            returnValue: _FakeUndoProvider_5(
              this,
              Invocation.getter(#undoProvider),
            ),
          )
          as _i7.UndoProvider);

  @override
  _i3.Offset get canvasCenter =>
      (super.noSuchMethod(
            Invocation.getter(#canvasCenter),
            returnValue: _FakeOffset_1(this, Invocation.getter(#canvasCenter)),
          )
          as _i3.Offset);

  @override
  bool get canvasResizeLockAspectRatio =>
      (super.noSuchMethod(
            Invocation.getter(#canvasResizeLockAspectRatio),
            returnValue: false,
          )
          as bool);

  @override
  _i4.ActionType get selectedAction =>
      (super.noSuchMethod(
            Invocation.getter(#selectedAction),
            returnValue: _i4.ActionType.pencil,
          )
          as _i4.ActionType);

  @override
  double get brushSize => (super.noSuchMethod(Invocation.getter(#brushSize), returnValue: 0.0) as double);

  @override
  _i4.BrushStyle get brushStyle =>
      (super.noSuchMethod(
            Invocation.getter(#brushStyle),
            returnValue: _i4.BrushStyle.solid,
          )
          as _i4.BrushStyle);

  @override
  _i3.Color get brushColor =>
      (super.noSuchMethod(
            Invocation.getter(#brushColor),
            returnValue: _FakeColor_6(this, Invocation.getter(#brushColor)),
          )
          as _i3.Color);

  @override
  _i3.Color get fillColor =>
      (super.noSuchMethod(
            Invocation.getter(#fillColor),
            returnValue: _FakeColor_6(this, Invocation.getter(#fillColor)),
          )
          as _i3.Color);

  @override
  int get tolerance => (super.noSuchMethod(Invocation.getter(#tolerance), returnValue: 0) as int);

  @override
  set canvasOffset(_i3.Offset? _canvasOffset) => super.noSuchMethod(
    Invocation.setter(#canvasOffset, _canvasOffset),
    returnValueForMissingStub: null,
  );

  @override
  set layers(_i4.LayersProvider? _layers) => super.noSuchMethod(
    Invocation.setter(#layers, _layers),
    returnValueForMissingStub: null,
  );

  @override
  set fillModel(_i5.FillModel? _fillModel) => super.noSuchMethod(
    Invocation.setter(#fillModel, _fillModel),
    returnValueForMissingStub: null,
  );

  @override
  set eyeDropPositionForBrush(_i3.Offset? _eyeDropPositionForBrush) => super.noSuchMethod(
    Invocation.setter(#eyeDropPositionForBrush, _eyeDropPositionForBrush),
    returnValueForMissingStub: null,
  );

  @override
  set eyeDropPositionForFill(_i3.Offset? _eyeDropPositionForFill) => super.noSuchMethod(
    Invocation.setter(#eyeDropPositionForFill, _eyeDropPositionForFill),
    returnValueForMissingStub: null,
  );

  @override
  set selectorModel(_i6.SelectorModel? _selectorModel) => super.noSuchMethod(
    Invocation.setter(#selectorModel, _selectorModel),
    returnValueForMissingStub: null,
  );

  @override
  set canvasResizeLockAspectRatio(bool? value) => super.noSuchMethod(
    Invocation.setter(#canvasResizeLockAspectRatio, value),
    returnValueForMissingStub: null,
  );

  @override
  set selectedAction(_i4.ActionType? value) => super.noSuchMethod(
    Invocation.setter(#selectedAction, value),
    returnValueForMissingStub: null,
  );

  @override
  set brushSize(double? value) => super.noSuchMethod(
    Invocation.setter(#brushSize, value),
    returnValueForMissingStub: null,
  );

  @override
  set brushStyle(_i4.BrushStyle? value) => super.noSuchMethod(
    Invocation.setter(#brushStyle, value),
    returnValueForMissingStub: null,
  );

  @override
  set brushColor(_i3.Color? value) => super.noSuchMethod(
    Invocation.setter(#brushColor, value),
    returnValueForMissingStub: null,
  );

  @override
  set fillColor(_i3.Color? value) => super.noSuchMethod(
    Invocation.setter(#fillColor, value),
    returnValueForMissingStub: null,
  );

  @override
  set tolerance(int? value) => super.noSuchMethod(
    Invocation.setter(#tolerance, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners => (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false) as bool);

  @override
  void canvasClear(_i3.Size? size) => super.noSuchMethod(
    Invocation.method(#canvasClear, [size]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Offset toCanvas(_i3.Offset? point) =>
      (super.noSuchMethod(
            Invocation.method(#toCanvas, [point]),
            returnValue: _FakeOffset_1(
              this,
              Invocation.method(#toCanvas, [point]),
            ),
          )
          as _i3.Offset);

  @override
  _i3.Offset fromCanvas(_i3.Offset? point) =>
      (super.noSuchMethod(
            Invocation.method(#fromCanvas, [point]),
            returnValue: _FakeOffset_1(
              this,
              Invocation.method(#fromCanvas, [point]),
            ),
          )
          as _i3.Offset);

  @override
  void applyScaleToCanvas({
    required double? scaleDelta,
    _i3.Offset? anchorPoint,
    bool? notifyListener = true,
  }) => super.noSuchMethod(
    Invocation.method(#applyScaleToCanvas, [], {
      #scaleDelta: scaleDelta,
      #anchorPoint: anchorPoint,
      #notifyListener: notifyListener,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void regionErase() => super.noSuchMethod(
    Invocation.method(#regionErase, []),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<void> regionCut() =>
      (super.noSuchMethod(
            Invocation.method(#regionCut, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> regionCopy() =>
      (super.noSuchMethod(
            Invocation.method(#regionCopy, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> paste() =>
      (super.noSuchMethod(
            Invocation.method(#paste, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void resetView() => super.noSuchMethod(
    Invocation.method(#resetView, []),
    returnValueForMissingStub: null,
  );

  @override
  void recordExecuteDrawingActionToSelectedLayer({
    required _i4.UserActionDrawing? action,
  }) => super.noSuchMethod(
    Invocation.method(#recordExecuteDrawingActionToSelectedLayer, [], {
      #action: action,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void undoAction() => super.noSuchMethod(
    Invocation.method(#undoAction, []),
    returnValueForMissingStub: null,
  );

  @override
  void redoAction() => super.noSuchMethod(
    Invocation.method(#redoAction, []),
    returnValueForMissingStub: null,
  );

  @override
  void canvasPan({
    required _i3.Offset? offsetDelta,
    bool? notifyListener = true,
  }) => super.noSuchMethod(
    Invocation.method(#canvasPan, [], {
      #offsetDelta: offsetDelta,
      #notifyListener: notifyListener,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void canvasFitToContainer({
    required double? containerWidth,
    required double? containerHeight,
  }) => super.noSuchMethod(
    Invocation.method(#canvasFitToContainer, [], {
      #containerWidth: containerWidth,
      #containerHeight: containerHeight,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void updateAction({
    _i3.Offset? start,
    required _i3.Offset? end,
    _i4.ActionType? type,
    _i3.Color? colorFill,
    _i3.Color? colorBrush,
  }) => super.noSuchMethod(
    Invocation.method(#updateAction, [], {
      #start: start,
      #end: end,
      #type: type,
      #colorFill: colorFill,
      #colorBrush: colorBrush,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void updateActionEnd(_i3.Offset? position) => super.noSuchMethod(
    Invocation.method(#updateActionEnd, [position]),
    returnValueForMissingStub: null,
  );

  @override
  void appendLineFromLastUserAction(_i3.Offset? positionEndOfNewLine) => super.noSuchMethod(
    Invocation.method(#appendLineFromLastUserAction, [
      positionEndOfNewLine,
    ]),
    returnValueForMissingStub: null,
  );

  @override
  void floodFillSolidAction(_i3.Offset? position) => super.noSuchMethod(
    Invocation.method(#floodFillSolidAction, [position]),
    returnValueForMissingStub: null,
  );

  @override
  void floodFillGradientAction(_i5.FillModel? fillModel) => super.noSuchMethod(
    Invocation.method(#floodFillGradientAction, [fillModel]),
    returnValueForMissingStub: null,
  );

  @override
  void updateGradientFill() => super.noSuchMethod(
    Invocation.method(#updateGradientFill, []),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<_i8.Region> getRegionPathFromLayerImage(_i3.Offset? position) =>
      (super.noSuchMethod(
            Invocation.method(#getRegionPathFromLayerImage, [position]),
            returnValue: _i11.Future<_i8.Region>.value(
              _FakeRegion_7(
                this,
                Invocation.method(#getRegionPathFromLayerImage, [position]),
              ),
            ),
          )
          as _i11.Future<_i8.Region>);

  @override
  bool isReadyForDrawing() =>
      (super.noSuchMethod(
            Invocation.method(#isReadyForDrawing, []),
            returnValue: false,
          )
          as bool);

  @override
  void selectorCreationStart(_i3.Offset? position) => super.noSuchMethod(
    Invocation.method(#selectorCreationStart, [position]),
    returnValueForMissingStub: null,
  );

  @override
  void selectorCreationAdditionalPoint(_i3.Offset? position) => super.noSuchMethod(
    Invocation.method(#selectorCreationAdditionalPoint, [position]),
    returnValueForMissingStub: null,
  );

  @override
  void selectorCreationEnd() => super.noSuchMethod(
    Invocation.method(#selectorCreationEnd, []),
    returnValueForMissingStub: null,
  );

  @override
  void selectAll() => super.noSuchMethod(
    Invocation.method(#selectAll, []),
    returnValueForMissingStub: null,
  );

  @override
  void crop() => super.noSuchMethod(
    Invocation.method(#crop, []),
    returnValueForMissingStub: null,
  );

  @override
  void newDocumentFromClipboardImage() => super.noSuchMethod(
    Invocation.method(#newDocumentFromClipboardImage, []),
    returnValueForMissingStub: null,
  );

  @override
  void update() => super.noSuchMethod(
    Invocation.method(#update, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ShellProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockShellProvider extends _i1.Mock implements _i12.ShellProvider {
  MockShellProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get loadedFileName =>
      (super.noSuchMethod(
            Invocation.getter(#loadedFileName),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#loadedFileName),
            ),
          )
          as String);

  @override
  bool get deviceSizeSmall =>
      (super.noSuchMethod(
            Invocation.getter(#deviceSizeSmall),
            returnValue: false,
          )
          as bool);

  @override
  _i14.CanvasAutoPlacement get canvasPlacement =>
      (super.noSuchMethod(
            Invocation.getter(#canvasPlacement),
            returnValue: _i14.CanvasAutoPlacement.fit,
          )
          as _i14.CanvasAutoPlacement);

  @override
  _i12.ShellMode get shellMode =>
      (super.noSuchMethod(
            Invocation.getter(#shellMode),
            returnValue: _i12.ShellMode.hidden,
          )
          as _i12.ShellMode);

  @override
  bool get isSidePanelExpanded =>
      (super.noSuchMethod(
            Invocation.getter(#isSidePanelExpanded),
            returnValue: false,
          )
          as bool);

  @override
  bool get showMenu => (super.noSuchMethod(Invocation.getter(#showMenu), returnValue: false) as bool);

  @override
  set loadedFileName(String? _loadedFileName) => super.noSuchMethod(
    Invocation.setter(#loadedFileName, _loadedFileName),
    returnValueForMissingStub: null,
  );

  @override
  set deviceSizeSmall(bool? _deviceSizeSmall) => super.noSuchMethod(
    Invocation.setter(#deviceSizeSmall, _deviceSizeSmall),
    returnValueForMissingStub: null,
  );

  @override
  set canvasPlacement(_i14.CanvasAutoPlacement? _canvasPlacement) => super.noSuchMethod(
    Invocation.setter(#canvasPlacement, _canvasPlacement),
    returnValueForMissingStub: null,
  );

  @override
  set shellMode(_i12.ShellMode? _shellMode) => super.noSuchMethod(
    Invocation.setter(#shellMode, _shellMode),
    returnValueForMissingStub: null,
  );

  @override
  set isSidePanelExpanded(bool? value) => super.noSuchMethod(
    Invocation.setter(#isSidePanelExpanded, value),
    returnValueForMissingStub: null,
  );

  @override
  set showMenu(bool? value) => super.noSuchMethod(
    Invocation.setter(#showMenu, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners => (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false) as bool);

  @override
  void update() => super.noSuchMethod(
    Invocation.method(#update, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AppPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppPreferences extends _i1.Mock implements _i2.AppPreferences {
  MockAppPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoaded => (super.noSuchMethod(Invocation.getter(#isLoaded), returnValue: false) as bool);

  @override
  double get sidePanelDistance =>
      (super.noSuchMethod(
            Invocation.getter(#sidePanelDistance),
            returnValue: 0.0,
          )
          as double);

  @override
  double get brushSize => (super.noSuchMethod(Invocation.getter(#brushSize), returnValue: 0.0) as double);

  @override
  _i3.Color get brushColor =>
      (super.noSuchMethod(
            Invocation.getter(#brushColor),
            returnValue: _FakeColor_6(this, Invocation.getter(#brushColor)),
          )
          as _i3.Color);

  @override
  _i3.Color get fillColor =>
      (super.noSuchMethod(
            Invocation.getter(#fillColor),
            returnValue: _FakeColor_6(this, Invocation.getter(#fillColor)),
          )
          as _i3.Color);

  @override
  bool get useApplePencil =>
      (super.noSuchMethod(
            Invocation.getter(#useApplePencil),
            returnValue: false,
          )
          as bool);

  @override
  _i11.Future<_i9.SharedPreferences> getPref() =>
      (super.noSuchMethod(
            Invocation.method(#getPref, []),
            returnValue: _i11.Future<_i9.SharedPreferences>.value(
              _FakeSharedPreferences_8(this, Invocation.method(#getPref, [])),
            ),
          )
          as _i11.Future<_i9.SharedPreferences>);

  @override
  _i11.Future<void> setSidePanelDistance(double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setSidePanelDistance, [value]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> setBrushSize(double? size) =>
      (super.noSuchMethod(
            Invocation.method(#setBrushSize, [size]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> setBrushColor(_i3.Color? color) =>
      (super.noSuchMethod(
            Invocation.method(#setBrushColor, [color]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> setFillColor(_i3.Color? color) =>
      (super.noSuchMethod(
            Invocation.method(#setFillColor, [color]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> setUseApplePencil(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setUseApplePencil, [value]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i9.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Object? get(String? key) => (super.noSuchMethod(Invocation.method(#get, [key])) as Object?);

  @override
  bool? getBool(String? key) => (super.noSuchMethod(Invocation.method(#getBool, [key])) as bool?);

  @override
  int? getInt(String? key) => (super.noSuchMethod(Invocation.method(#getInt, [key])) as int?);

  @override
  double? getDouble(String? key) => (super.noSuchMethod(Invocation.method(#getDouble, [key])) as double?);

  @override
  String? getString(String? key) => (super.noSuchMethod(Invocation.method(#getString, [key])) as String?);

  @override
  bool containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: false,
          )
          as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(#getStringList, [key])) as List<String>?);

  @override
  _i11.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> commit() =>
      (super.noSuchMethod(
            Invocation.method(#commit, []),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [LayersProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockLayersProvider extends _i1.Mock implements _i4.LayersProvider {
  MockLayersProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i15.ColorUsage> get topColors =>
      (super.noSuchMethod(
            Invocation.getter(#topColors),
            returnValue: <_i15.ColorUsage>[],
          )
          as List<_i15.ColorUsage>);

  @override
  _i3.Size get size =>
      (super.noSuchMethod(
            Invocation.getter(#size),
            returnValue: _FakeSize_9(this, Invocation.getter(#size)),
          )
          as _i3.Size);

  @override
  double get width => (super.noSuchMethod(Invocation.getter(#width), returnValue: 0.0) as double);

  @override
  double get height => (super.noSuchMethod(Invocation.getter(#height), returnValue: 0.0) as double);

  @override
  bool get canvasResizeLockAspectRatio =>
      (super.noSuchMethod(
            Invocation.getter(#canvasResizeLockAspectRatio),
            returnValue: false,
          )
          as bool);

  @override
  double get scale => (super.noSuchMethod(Invocation.getter(#scale), returnValue: 0.0) as double);

  @override
  _i14.CanvasResizePosition get canvasResizePosition =>
      (super.noSuchMethod(
            Invocation.getter(#canvasResizePosition),
            returnValue: _i14.CanvasResizePosition.topLeft,
          )
          as _i14.CanvasResizePosition);

  @override
  int get length => (super.noSuchMethod(Invocation.getter(#length), returnValue: 0) as int);

  @override
  bool get isEmpty => (super.noSuchMethod(Invocation.getter(#isEmpty), returnValue: false) as bool);

  @override
  bool get isNotEmpty => (super.noSuchMethod(Invocation.getter(#isNotEmpty), returnValue: false) as bool);

  @override
  bool get hasChanged => (super.noSuchMethod(Invocation.getter(#hasChanged), returnValue: false) as bool);

  @override
  int get selectedLayerIndex =>
      (super.noSuchMethod(
            Invocation.getter(#selectedLayerIndex),
            returnValue: 0,
          )
          as int);

  @override
  _i4.LayerProvider get selectedLayer =>
      (super.noSuchMethod(
            Invocation.getter(#selectedLayer),
            returnValue: _FakeLayerProvider_10(
              this,
              Invocation.getter(#selectedLayer),
            ),
          )
          as _i4.LayerProvider);

  @override
  List<_i4.LayerProvider> get list =>
      (super.noSuchMethod(
            Invocation.getter(#list),
            returnValue: <_i4.LayerProvider>[],
          )
          as List<_i4.LayerProvider>);

  @override
  set cachedImage(_i3.Image? _cachedImage) => super.noSuchMethod(
    Invocation.setter(#cachedImage, _cachedImage),
    returnValueForMissingStub: null,
  );

  @override
  set topColors(List<_i15.ColorUsage>? _topColors) => super.noSuchMethod(
    Invocation.setter(#topColors, _topColors),
    returnValueForMissingStub: null,
  );

  @override
  set size(_i3.Size? size) => super.noSuchMethod(
    Invocation.setter(#size, size),
    returnValueForMissingStub: null,
  );

  @override
  set canvasResizeLockAspectRatio(bool? value) => super.noSuchMethod(
    Invocation.setter(#canvasResizeLockAspectRatio, value),
    returnValueForMissingStub: null,
  );

  @override
  set scale(double? value) => super.noSuchMethod(
    Invocation.setter(#scale, value),
    returnValueForMissingStub: null,
  );

  @override
  set canvasResizePosition(_i14.CanvasResizePosition? value) => super.noSuchMethod(
    Invocation.setter(#canvasResizePosition, value),
    returnValueForMissingStub: null,
  );

  @override
  set selectedLayerIndex(int? index) => super.noSuchMethod(
    Invocation.setter(#selectedLayerIndex, index),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners => (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false) as bool);

  @override
  void update() => super.noSuchMethod(
    Invocation.method(#update, []),
    returnValueForMissingStub: null,
  );

  @override
  void canvasResize(
    int? width,
    int? height,
    _i14.CanvasResizePosition? position,
  ) => super.noSuchMethod(
    Invocation.method(#canvasResize, [width, height, position]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.LayerProvider addWhiteBackgroundLayer() =>
      (super.noSuchMethod(
            Invocation.method(#addWhiteBackgroundLayer, []),
            returnValue: _FakeLayerProvider_10(
              this,
              Invocation.method(#addWhiteBackgroundLayer, []),
            ),
          )
          as _i4.LayerProvider);

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  void layersToggleVisibility(_i4.LayerProvider? layer) => super.noSuchMethod(
    Invocation.method(#layersToggleVisibility, [layer]),
    returnValueForMissingStub: null,
  );

  @override
  void clearHasChanged() => super.noSuchMethod(
    Invocation.method(#clearHasChanged, []),
    returnValueForMissingStub: null,
  );

  @override
  bool isIndexInRange(int? indexLayer) =>
      (super.noSuchMethod(
            Invocation.method(#isIndexInRange, [indexLayer]),
            returnValue: false,
          )
          as bool);

  @override
  int getLayerIndex(_i4.LayerProvider? layer) =>
      (super.noSuchMethod(
            Invocation.method(#getLayerIndex, [layer]),
            returnValue: 0,
          )
          as int);

  @override
  _i4.LayerProvider get(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#get, [index]),
            returnValue: _FakeLayerProvider_10(
              this,
              Invocation.method(#get, [index]),
            ),
          )
          as _i4.LayerProvider);

  @override
  _i4.LayerProvider newLayer(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#newLayer, [name]),
            returnValue: _FakeLayerProvider_10(
              this,
              Invocation.method(#newLayer, [name]),
            ),
          )
          as _i4.LayerProvider);

  @override
  void ensureLayerAtIndex(int? index) => super.noSuchMethod(
    Invocation.method(#ensureLayerAtIndex, [index]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.LayerProvider? getByName(String? name) =>
      (super.noSuchMethod(Invocation.method(#getByName, [name])) as _i4.LayerProvider?);

  @override
  _i4.LayerProvider addTop({String? name}) =>
      (super.noSuchMethod(
            Invocation.method(#addTop, [], {#name: name}),
            returnValue: _FakeLayerProvider_10(
              this,
              Invocation.method(#addTop, [], {#name: name}),
            ),
          )
          as _i4.LayerProvider);

  @override
  _i4.LayerProvider addBottom([String? name]) =>
      (super.noSuchMethod(
            Invocation.method(#addBottom, [name]),
            returnValue: _FakeLayerProvider_10(
              this,
              Invocation.method(#addBottom, [name]),
            ),
          )
          as _i4.LayerProvider);

  @override
  void insert(int? index, _i4.LayerProvider? layerToInsert) => super.noSuchMethod(
    Invocation.method(#insert, [index, layerToInsert]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.LayerProvider insertAt(int? index, [String? name]) =>
      (super.noSuchMethod(
            Invocation.method(#insertAt, [index, name]),
            returnValue: _FakeLayerProvider_10(
              this,
              Invocation.method(#insertAt, [index, name]),
            ),
          )
          as _i4.LayerProvider);

  @override
  bool remove(_i4.LayerProvider? layer) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [layer]),
            returnValue: false,
          )
          as bool);

  @override
  void removeByIndex(int? index) => super.noSuchMethod(
    Invocation.method(#removeByIndex, [index]),
    returnValueForMissingStub: null,
  );

  @override
  void mergeLayers(int? indexFrom, int? indexTo) => super.noSuchMethod(
    Invocation.method(#mergeLayers, [indexFrom, indexTo]),
    returnValueForMissingStub: null,
  );

  @override
  void offsetContent(_i3.Offset? offset) => super.noSuchMethod(
    Invocation.method(#offsetContent, [offset]),
    returnValueForMissingStub: null,
  );

  @override
  void hideShowAllExcept(_i4.LayerProvider? exceptLayer, bool? show) => super.noSuchMethod(
    Invocation.method(#hideShowAllExcept, [exceptLayer, show]),
    returnValueForMissingStub: null,
  );

  @override
  void evaluatTopColor() => super.noSuchMethod(
    Invocation.method(#evaluatTopColor, []),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<List<_i15.ColorUsage>> getTopColorUsed() =>
      (super.noSuchMethod(
            Invocation.method(#getTopColorUsed, []),
            returnValue: _i11.Future<List<_i15.ColorUsage>>.value(
              <_i15.ColorUsage>[],
            ),
          )
          as _i11.Future<List<_i15.ColorUsage>>);

  @override
  _i11.Future<_i3.Image> capturePainterToImage() =>
      (super.noSuchMethod(
            Invocation.method(#capturePainterToImage, []),
            returnValue: _i11.Future<_i3.Image>.value(
              _FakeImage_11(
                this,
                Invocation.method(#capturePainterToImage, []),
              ),
            ),
          )
          as _i11.Future<_i3.Image>);

  @override
  _i11.Future<_i16.Uint8List> capturePainterToImageBytes() =>
      (super.noSuchMethod(
            Invocation.method(#capturePainterToImageBytes, []),
            returnValue: _i11.Future<_i16.Uint8List>.value(_i16.Uint8List(0)),
          )
          as _i11.Future<_i16.Uint8List>);

  @override
  _i11.Future<_i3.Color?> getColorAtOffset(_i3.Offset? offset) =>
      (super.noSuchMethod(
            Invocation.method(#getColorAtOffset, [offset]),
            returnValue: _i11.Future<_i3.Color?>.value(),
          )
          as _i11.Future<_i3.Color?>);

  @override
  void addListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
