import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:fpaint/files/webp_encoder.dart';
import 'package:fpaint/helpers/constants.dart';
import 'package:image/image.dart' as img;

/// Minimum valid RIFF/WebP/VP8L file size:
/// 4 (RIFF) + 4 (size) + 4 (WEBP) + 4 (VP8L) + 4 (chunk size) + body.
const int _minWebpFileSize = 20;

/// Byte offset where the VP8L chunk tag appears in the container.
const int _vp8lTagOffset = 12;

/// Number of RGBA bytes per pixel.
const int _bytesPerPixel = 4;

/// Output file generated by this test suite.
const String _finalWebpOutputPath = 'test/final.webp';

void main() {
  group('WebP Encoder Tests', () {
    test('encodeWebpLossless function exists', () {
      expect(encodeWebpLossless, isNotNull);
    });

    test('encodes a 1x1 red pixel into a valid RIFF WebP container', () {
      // 1 pixel: R=255, G=0, B=0, A=255
      final Uint8List rgba = Uint8List.fromList(<int>[255, 0, 0, 255]);

      final Uint8List result = encodeWebpLossless(rgba, 1, 1);

      expect(result.length, greaterThanOrEqualTo(_minWebpFileSize));

      // RIFF header
      expect(result[0], WebPConstants.riffTag[0]); // R
      expect(result[1], WebPConstants.riffTag[1]); // I
      expect(result[2], WebPConstants.riffTag[2]); // F
      expect(result[3], WebPConstants.riffTag[3]); // F

      // WEBP tag at offset 8
      expect(result[8], WebPConstants.webpTag[0]); // W
      expect(result[9], WebPConstants.webpTag[1]); // E
      expect(result[10], WebPConstants.webpTag[2]); // B
      expect(result[11], WebPConstants.webpTag[3]); // P

      // VP8L chunk tag at offset 12
      expect(result[_vp8lTagOffset], WebPConstants.vp8lTag[0]); // V
      expect(result[_vp8lTagOffset + 1], WebPConstants.vp8lTag[1]); // P
      expect(result[_vp8lTagOffset + 2], WebPConstants.vp8lTag[2]); // 8
      expect(result[_vp8lTagOffset + 3], WebPConstants.vp8lTag[3]); // L

      final img.Image? decoded = img.decodeWebP(result);
      expect(decoded, isNotNull);
      expect(decoded!.width, 1);
      expect(decoded.height, 1);
      final img.Pixel pixel = decoded.getPixel(0, 0);
      expect(pixel.r.toInt(), 255);
      expect(pixel.g.toInt(), 0);
      expect(pixel.b.toInt(), 0);
      expect(pixel.a.toInt(), 255);
    });

    test('RIFF size field is consistent with file length', () {
      final Uint8List rgba = Uint8List(_bytesPerPixel * 4); // 2x2 transparent
      final Uint8List result = encodeWebpLossless(rgba, 2, 2);

      // RIFF size (little-endian u32 at offset 4) = file length - 8.
      final ByteData bd = ByteData.sublistView(result);
      final int riffSize = bd.getUint32(4, Endian.little);
      expect(riffSize, result.length - WebPConstants.chunkHeaderSize);
    });

    test('VP8L body starts with signature byte 0x2F', () {
      final Uint8List rgba = Uint8List.fromList(<int>[0, 0, 0, 255]);
      final Uint8List result = encodeWebpLossless(rgba, 1, 1);

      // VP8L body begins right after the chunk header (offset 20).
      const int vp8lBodyOffset = _minWebpFileSize;
      expect(result[vp8lBodyOffset], WebPConstants.vp8lSignature);
    });

    test('encodes a 2x2 white image', () {
      // 4 opaque white pixels
      final Uint8List rgba = Uint8List(_bytesPerPixel * 4);
      for (int i = 0; i < 4; i++) {
        rgba[i * _bytesPerPixel] = 255; // R
        rgba[i * _bytesPerPixel + 1] = 255; // G
        rgba[i * _bytesPerPixel + 2] = 255; // B
        rgba[i * _bytesPerPixel + 3] = 255; // A
      }

      final Uint8List result = encodeWebpLossless(rgba, 2, 2);
      expect(result.length, greaterThan(_minWebpFileSize));

      // Verify RIFF + WEBP tags are intact
      expect(String.fromCharCodes(result.sublist(0, 4)), 'RIFF');
      expect(String.fromCharCodes(result.sublist(8, 12)), 'WEBP');
    });

    test('larger image produces proportionally larger output', () {
      const int smallSide = 2;
      const int largeSide = 8;

      final Uint8List smallRgba = Uint8List(
        smallSide * smallSide * _bytesPerPixel,
      );
      final Uint8List largeRgba = Uint8List(
        largeSide * largeSide * _bytesPerPixel,
      );

      final Uint8List smallResult = encodeWebpLossless(smallRgba, smallSide, smallSide);
      final Uint8List largeResult = encodeWebpLossless(largeRgba, largeSide, largeSide);

      expect(largeResult.length, greaterThan(smallResult.length));
    });

    test('different pixel data produces different output', () {
      const int side = 2;
      final Uint8List black = Uint8List(side * side * _bytesPerPixel);
      final Uint8List white = Uint8List(side * side * _bytesPerPixel);
      for (int i = 0; i < white.length; i++) {
        white[i] = 255;
      }

      final Uint8List resultBlack = encodeWebpLossless(black, side, side);
      final Uint8List resultWhite = encodeWebpLossless(white, side, side);

      // Both are valid WebP files but differ in the VP8L body
      expect(resultBlack, isNot(equals(resultWhite)));
    });

    test('writes final.webp to test output path', () async {
      const int side = 2;
      final Uint8List rgba = Uint8List(side * side * _bytesPerPixel);
      for (int i = 0; i < rgba.length; i++) {
        rgba[i] = 255;
      }

      final Uint8List encoded = encodeWebpLossless(rgba, side, side);

      final File outputFile = File(_finalWebpOutputPath);
      await outputFile.writeAsBytes(encoded, flush: true);

      expect(await outputFile.exists(), isTrue);

      final Uint8List writtenBytes = await outputFile.readAsBytes();
      expect(writtenBytes.length, greaterThanOrEqualTo(_minWebpFileSize));
      expect(writtenBytes[0], WebPConstants.riffTag[0]);
      expect(writtenBytes[1], WebPConstants.riffTag[1]);
      expect(writtenBytes[2], WebPConstants.riffTag[2]);
      expect(writtenBytes[3], WebPConstants.riffTag[3]);
      expect(writtenBytes[8], WebPConstants.webpTag[0]);
      expect(writtenBytes[9], WebPConstants.webpTag[1]);
      expect(writtenBytes[10], WebPConstants.webpTag[2]);
      expect(writtenBytes[11], WebPConstants.webpTag[3]);
    });

    test('asserts on mismatched rgba length', () {
      // 3 bytes is too few for a 1x1 image (needs 4)
      final Uint8List shortRgba = Uint8List(3);

      expect(
        () => encodeWebpLossless(shortRgba, 1, 1),
        throwsA(isA<AssertionError>()),
      );
    });
  });
}
