// GENERATED FILE. DO NOT EDIT.
// Generated by `tool/check.sh` from `pubspec.yaml`.

const String packageVersion = '1.9.4';
const String packageBuildNumber = '1';
const String packageVersionWithBuild = '1.9.4+1';
