// GENERATED FILE. DO NOT EDIT.
// Generated by `tool/check.sh` from `pubspec.yaml`.

const String packageVersion = '2.0.2';
const String packageBuildNumber = '';
const String packageVersionWithBuild = '2.0.2';
