/// GENERATED FILE. DO NOT EDIT.
/// Generated by `tool/check.sh` from `pubspec.yaml`.
library;

const String packageVersion = '1.8.5';
const String packageBuildNumber = '1';
const String packageVersionWithBuild = '1.8.5+1';
