#!/bin/sh

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CHECK_FAILURE_EXIT_CODE="1"
FCHECK_VERSION="1.4.1"
TEST_OUTPUT_DIR="$ROOT_DIR/test/output"
COVERAGE_LCOV_FILE="$ROOT_DIR/coverage/lcov.info"
COVERAGE_SUMMARY_FILE="$TEST_OUTPUT_DIR/cc.txt"
MINIMUM_COVERAGE_PERCENTAGE="85.1"
VERSION_FILE="$ROOT_DIR/lib/models/version.dart"
DEPENDENCY_VERSIONS_FILE="$ROOT_DIR/lib/models/dependency_versions.dart"
PUBSPEC_LOCK_FILE="$ROOT_DIR/pubspec.lock"
ANSI_RED="$(printf '\033[31m')"
ANSI_BOLD="$(printf '\033[1m')"
ANSI_BLINK="$(printf '\033[5m')"
ANSI_RESET="$(printf '\033[0m')"

cd "$ROOT_DIR"

extract_pubspec_version() {
	awk '
		/^version:[[:space:]]*/ {
			value = $0
			sub(/^version:[[:space:]]*/, "", value)
			print value
			exit
		}
	' "$ROOT_DIR/pubspec.yaml"
}

write_version_model() {
	raw_version="$1"
	version_without_build="${raw_version%%+*}"
	build_number=""
	if [ "$raw_version" != "$version_without_build" ]; then
		build_number="${raw_version#*+}"
	fi

	temp_file="$(mktemp)"
	cat > "$temp_file" <<EOF
// GENERATED FILE. DO NOT EDIT.
// Generated by \`tool/check.sh\` from \`pubspec.yaml\`.

const String packageVersion = '$version_without_build';
const String packageBuildNumber = '$build_number';
const String packageVersionWithBuild = '$raw_version';
EOF

	if [ ! -f "$VERSION_FILE" ] || ! cmp -s "$temp_file" "$VERSION_FILE"; then
		mkdir -p "$(dirname "$VERSION_FILE")"
		mv "$temp_file" "$VERSION_FILE"
	else
		rm "$temp_file"
	fi
}

extract_dependency_versions() {
	awk '
		/^packages:[[:space:]]*$/ {
			inside_packages = 1
			next
		}
		inside_packages && /^[^[:space:]]/ {
			inside_packages = 0
		}
		inside_packages && /^  [^[:space:]][^:]*:[[:space:]]*$/ {
			package_name = $0
			sub(/^  /, "", package_name)
			sub(/:[[:space:]]*$/, "", package_name)
			next
		}
		inside_packages && package_name != "" && /^    version:[[:space:]]*/ {
			version_value = $0
			sub(/^    version:[[:space:]]*/, "", version_value)
			gsub(/"/, "", version_value)
			print package_name "|" version_value
			package_name = ""
		}
	' "$PUBSPEC_LOCK_FILE"
}

write_dependency_versions_model() {
	if [ ! -f "$PUBSPEC_LOCK_FILE" ]; then
		echo "pubspec.lock not found: $PUBSPEC_LOCK_FILE"
		exit "$CHECK_FAILURE_EXIT_CODE"
	fi

	temp_file="$(mktemp)"
	temp_pairs_file="$(mktemp)"
	extract_dependency_versions | LC_ALL=C sort > "$temp_pairs_file"

	cat > "$temp_file" <<EOF
// GENERATED FILE. DO NOT EDIT.
// Generated by \`tool/check.sh\` from \`pubspec.lock\`.
// coverage:ignore-file

const Map<String, String> dependencyVersions = <String, String>{
EOF

	while IFS='|' read -r package_name package_version; do
		escaped_package_name="$(printf '%s' "$package_name" | sed "s/'/\\\\'/g")"
		escaped_package_version="$(printf '%s' "$package_version" | sed "s/'/\\\\'/g")"
		printf "  '%s': '%s',\n" "$escaped_package_name" "$escaped_package_version" >> "$temp_file"
	done < "$temp_pairs_file"

	cat >> "$temp_file" <<EOF
};
EOF

	rm "$temp_pairs_file"

	if [ ! -f "$DEPENDENCY_VERSIONS_FILE" ] || ! cmp -s "$temp_file" "$DEPENDENCY_VERSIONS_FILE"; then
		mkdir -p "$(dirname "$DEPENDENCY_VERSIONS_FILE")"
		mv "$temp_file" "$DEPENDENCY_VERSIONS_FILE"
	else
		rm "$temp_file"
	fi
}

echo --- Generate Version Model
PUBSPEC_VERSION="$(extract_pubspec_version)"
if [ -z "$PUBSPEC_VERSION" ]; then
	echo "Unable to read version from pubspec.yaml"
	exit "$CHECK_FAILURE_EXIT_CODE"
fi
write_version_model "$PUBSPEC_VERSION"

show_fcheck_score_error() {
	printf '\n%s%s%s' "$ANSI_RED" "$ANSI_BOLD" "$ANSI_BLINK"
	cat <<'EOF'
################################################################
############### Expected fCheck SCORE of 100%   ################
############### Fix the remaining fCheck issues ################
################################################################
EOF
	printf '%s\n\n' "$ANSI_RESET"
}

echo --- Pub Get
flutter pub get > /dev/null || { echo "Pub get failed"; exit 1; }
echo --- Generate Dependency Versions Model
write_dependency_versions_model
echo --- Pub Outdated
flutter pub outdated

echo --- fCheck
# Install the pinned version into the isolated cache, then run it.
# Note: `dart pub cache exec` doesn't exist on all Dart SDK versions; `pub global run` does.
dart pub global activate fcheck "$FCHECK_VERSION" > /dev/null
dart pub global run fcheck --strict --svg --fix --list full
fcheck_exit_code="$?"

case "$fcheck_exit_code" in
	0)
		;;
	[1-9]|[1-9][0-9])
		show_fcheck_score_error
		;;
	*)
		echo "fCheck failed"
		exit "$CHECK_FAILURE_EXIT_CODE"
		;;
esac

echo --- Format sources
dart format lib test tool
dart fix --apply

if [ "$fcheck_exit_code" -ne 0 ]; then
	exit "$CHECK_FAILURE_EXIT_CODE"
fi

echo --- Analyze
flutter analyze lib test --no-pub

echo --- Test
test_started_at="$(date +%s)"
test_output="$(flutter test --reporter=compact --coverage --no-pub 2>&1)"
test_exit_code="$?"
test_finished_at="$(date +%s)"
test_elapsed_seconds="$((test_finished_at - test_started_at))"
test_elapsed_minutes="$((test_elapsed_seconds / 60))"
test_elapsed_remaining_seconds="$((test_elapsed_seconds % 60))"
printf '%s %sm %ss\n' '--- Test Duration:' "$test_elapsed_minutes" "$test_elapsed_remaining_seconds"

if [ "$test_exit_code" -ne 0 ]; then
	echo "$test_output"
	exit "$CHECK_FAILURE_EXIT_CODE"
fi

echo --- Coverage Summary
if [ ! -f "$COVERAGE_LCOV_FILE" ]; then
	echo "Coverage file not found: $COVERAGE_LCOV_FILE"
	exit "$CHECK_FAILURE_EXIT_CODE"
fi

if [ ! -s "$COVERAGE_LCOV_FILE" ]; then
	echo "Coverage file is empty: $COVERAGE_LCOV_FILE"
	exit "$CHECK_FAILURE_EXIT_CODE"
fi

if ! grep -q "^LF:" "$COVERAGE_LCOV_FILE"; then
	echo "Coverage file does not contain line totals: $COVERAGE_LCOV_FILE"
	exit "$CHECK_FAILURE_EXIT_CODE"
fi

COVERAGE_PERCENTAGE="$(awk -F: '
	/^LF:/ { line_found += $2; next }
	/^LH:/ { line_hit += $2; next }
	END {
		if (line_found <= 0) {
			exit 1
		}
		printf "%.1f%%", (line_hit / line_found) * 100
	}
' "$COVERAGE_LCOV_FILE")" || {
	echo "Coverage file does not contain valid line totals: $COVERAGE_LCOV_FILE"
	exit "$CHECK_FAILURE_EXIT_CODE"
}

mkdir -p "$TEST_OUTPUT_DIR"
printf '%s\n' "$COVERAGE_PERCENTAGE" | tee "$COVERAGE_SUMMARY_FILE"

echo --- Coverage Threshold
COVERAGE_PERCENTAGE_VALUE="$(printf '%s' "$COVERAGE_PERCENTAGE" | tr -d '%')"
if ! awk -v current="$COVERAGE_PERCENTAGE_VALUE" -v minimum="$MINIMUM_COVERAGE_PERCENTAGE" 'BEGIN { exit(current + 0 >= minimum + 0 ? 0 : 1) }'; then
	echo "Coverage regression: $COVERAGE_PERCENTAGE is below required minimum ${MINIMUM_COVERAGE_PERCENTAGE}%"
	exit "$CHECK_FAILURE_EXIT_CODE"
fi
