#!/bin/bash
set -e

# Ensure Flutter SDK is in PATH (adjust path if necessary - this should be handled by the calling environment)
# export PATH="$PATH:/opt/flutter/bin"

# Ensure packages are up-to-date
flutter pub get

# Run tests and collect coverage data
flutter test --coverage

# List files in coverage directory to see what's generated
echo "Contents of coverage directory:"
ls -la coverage/

# Convert coverage data to LCOV format
# Check if coverage/lcov.info exists, if not, create it
if [ ! -f coverage/lcov.info ]; then
  # Create the directory if it doesn't exist
  mkdir -p coverage
  # Create an empty lcov.info file, genhtml will not work otherwise
  # touch coverage/lcov.info # This might not be needed if flutter test --coverage creates it
fi

# Figure out the correct input file.
# It's often coverage/test_collector.dill or directly lcov.info
INPUT_COVERAGE_FILE=""
if [ -f "coverage/lcov.info" ] && [ $(grep -c "^SF:" "coverage/lcov.info") -gt 0 ]; then
    echo "coverage/lcov.info already exists and seems valid. Skipping format_coverage."
    # If lcov.info is already there and populated, we might not need to run format_coverage
    # However, the task is to ensure the script *generates* it.
    # Let's assume we still want to run format_coverage from the raw data if possible.
    # The prompt implies we should use coverage:format_coverage
    # So, let's find the raw data file.
fi

# Common raw coverage data files
if [ -f "coverage/test_collector.dill" ]; then
    INPUT_COVERAGE_FILE="coverage/test_collector.dill"
elif [ -f "coverage/coverage_collector.log" ]; then # The one originally expected
    INPUT_COVERAGE_FILE="coverage/coverage_collector.log"
# Add other potential names if necessary
fi

if [ -n "$INPUT_COVERAGE_FILE" ]; then
    echo "Using $INPUT_COVERAGE_FILE as input for format_coverage."
    # Use pub run to execute the coverage package tool
    flutter pub run coverage:format_coverage --lcov -i "$INPUT_COVERAGE_FILE" -o coverage/lcov.info --report-on=lib
else
    if [ -f "coverage/lcov.info" ] && [ $(grep -c "^SF:" "coverage/lcov.info") -gt 0 ]; then
        echo "coverage/lcov.info appears to be already generated by 'flutter test --coverage'. No further formatting needed."
    else
        echo "Error: Could not find a suitable coverage data file (e.g., test_collector.dill, coverage_collector.log) and lcov.info was not pre-generated or is empty."
        exit 1
    fi
fi

echo "LCOV report should be available at coverage/lcov.info"
# Verify it exists and is not empty
if [ -f "coverage/lcov.info" ] && [ -s "coverage/lcov.info" ]; then
  echo "Successfully generated coverage/lcov.info"
else
  echo "Failed to generate or find a valid coverage/lcov.info"
  exit 1
fi
